# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6dfcabfa045820a17a782cbaca41f9c2239e6e433114cb590bdc3ece2281c56f54bf4c6f6ae3ef9f6849ad1583b2badefd0dc42180d114e8921bd1c9ad8229ab

test:
  secret_key_base: 119a49e959251213fbe7d339cd64eeaca870600bf71b841e0ec1eafd7a1cc5c1e21f6ec839a430614dd2b7fb1ca6e64657f387afcce1d69815a05026a7eacf24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
